repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: elastic
  url: https://helm.elastic.co/
- name: nuxeo
  url: https://chartmuseum.platform.dev.nuxeo.com/

helmDefaults:
  atomic: true
  timeout: 300
  wait: true

releases:
- name: nuxeo
  chart: nuxeo/nuxeo
  version: ~3.0.1
  values:
  - values-nuxeo.yaml.gotmpl
- name: mongodb
  chart: bitnami/mongodb
  version: 7.14.2
  values:
  - values-mongodb.yaml
- name: elasticsearch
  chart: elastic/elasticsearch
  version: 7.9.2
  values:
  - values-elasticsearch.yaml
- name: kafka
  chart: bitnami/kafka
  version: 11.8.8
  values:
  - values-kafka.yaml
