{{- $isAfter123 := (semverCompare ">=1.23.0" .Capabilities.KubeVersion.GitVersion) -}}
{{- if .Values.ingress.enabled -}}
apiVersion: {{ ternary "networking.k8s.io/v1" "networking.k8s.io/v1beta1" $isAfter123 }}
kind: Ingress
metadata:
  name: {{ template "nuxeo.fullname" . }}
  labels:
    app: {{ template "nuxeo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - backend:
              {{- if $isAfter123 }}
              service:
                name: {{ template "nuxeo.fullname" . }}
                port:
                  number: {{ .Values.service.externalPort}}
              {{- else }}
              serviceName: {{ template "nuxeo.fullname" . }}
              servicePort: {{ .Values.service.externalPort}}
              {{- end }}
            {{- if .Values.ingress.path }}
            path: {{ .Values.ingress.path }}
            {{- end }}
            {{- if $isAfter123 }}
            pathType: ImplementationSpecific
            {{- end }}
      {{- with .Values.ingress.hostname }}
      host: {{ toYaml . }}
      {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
