{{- if .Values.persistentVolumeStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nuxeo.fullname" . }}-binaries
  labels: {{- include "nuxeo.labels" . | nindent 4 }}
{{- with .Values.persistentVolumeStorage.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.persistentVolumeStorage.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  accessModes: {{- toYaml .Values.persistentVolumeStorage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ required "persistentVolumeStorage.size is required" .Values.persistentVolumeStorage.size | quote }}
  {{- with .Values.persistentVolumeStorage.storageClass }}
  storageClassName: {{ toYaml . }}
  {{- end }}
{{- end }}
{{- if .Values.logs.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nuxeo.fullname" . }}-log
  labels: {{- include "nuxeo.labels" . | nindent 4 }}
{{- with .Values.logs.persistence.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.logs.persistence.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  accessModes: {{- toYaml .Values.logs.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ required "logs.persistence.size is required" .Values.logs.persistence.size | quote }}
  {{- with .Values.logs.persistence.storageClass }}
  storageClassName: {{ toYaml . }}
  {{- end }}
{{- end }}
