{{- if .Values.persistentVolumeStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nuxeo.fullname" . }}-binaries
  labels: {{- include "nuxeo.labels" . | nindent 4 }}
{{- with .Values.persistentVolumeStorage.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
  {{- if .Values.persistentVolumeStorage.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistentVolumeStorage.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
{{- with .Values.persistentVolumeStorage.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "persistentVolumeStorage.size is required" .Values.persistentVolumeStorage.size | quote }}
{{- end }}
{{- if .Values.logs.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nuxeo.fullname" . }}-log
  labels: {{- include "nuxeo.labels" . | nindent 4 }}
{{- with .Values.logs.persistence.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
  {{- if .Values.logs.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.logs.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
{{- with .Values.logs.persistence.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "logs.persistence.size is required" .Values.logs.persistence.size | quote }}
{{- end }}
