{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nuxeo.serviceAccountName" . }}
  labels: {{- include "nuxeo.labels" . | nindent 4 }}
{{- end -}}
