image:
  tag: "2021.x"
  pullSecrets:
  - name: kubernetes-docker-cfg
ingress:
  enabled: true
nodeSelector:
  team: platform
tolerations:
- effect: NoSchedule
  key: team
  operator: Equal
  value: platform
