dependencies:
  - name: elasticsearch
    version: 1.32.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nuxeo.elasticsearch.deploy
    alias: elasticsearch
    tags:
      - elasticsearch
  - name: kafka
    version: ~0.20.8
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: nuxeo.kafka.deploy
    alias: kafka
    tags:
      - kafka
  - name: mongodb
    version: ~7.14.2
    repository: https://charts.bitnami.com/bitnami
    condition: nuxeo.mongodb.deploy
    alias: mongodb
    tags:
      - mongodb
  - name: postgresql
    version: ~8.1.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nuxeo.postgresql.deploy
    alias: postgresql
    tags:
      - postgresql
  - name: redis
    version: ~10.3.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: redis
    condition: nuxeo.redis.deploy
    tags:
      - redis
